ALTER TABLE public.shifts
  ADD COLUMN IF NOT EXISTS allow_swap_requests BOOLEAN DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS require_attendance_report BOOLEAN DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS theme_color VARCHAR(20) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS is_series BOOLEAN NOT NULL DEFAULT FALSE;
